promptToReturnFromSubprocess: false
os:
  # Opens files in existing nvim instance (when running lazygit inside nvim terminal)
  editPreset: nvim-remote
gui:
  filterMode: fuzzy
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
